In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('dataset/multiTimeline.csv')

In [7]:
df

     year  variableA  variableB  variableC  variableD
0    2004         26          2         78          0
1    2004         36          2         91          0
2    2004         35          1        100          0
3    2004         32          2        100          0
4    2004         35          2         94          0
5    2004         31          2         76          0
6    2004         20          2         68          0
7    2004         31          2         87          0
8    2004         40          2         85          0
9    2004         32          1         79          0
10   2004         29          2         75          0
11   2004         18          2         67          0
12   2005         19          2         62          0
13   2005         26          2         63          0
14   2005         23          2         69          0
15   2005         29          1         72          0
16   2005         26          2         66          0
17   2005         23          2         54          0
18   2005         13          2         48          0
19   2005         22          2         53          0
20   2005         33          2         58          0
21   2005         25          2         52          0
22   2005         23          2         57          0
23   2005         12          2         52          0
24   2006         10          2         42          0
25   2006         14          2         47          1
26   2006         15          3         50          1
27   2006         15          2         48          1
28   2006         18          1         49          1
29   2006         13          2         46          1
..    ...        ...        ...        ...        ...
153  2016          7         60         13         35
154  2016          7         65         15         39
155  2016          5         55         13         33
156  2017          6         59         13         36
157  2017          7         66         14         40
158  2017          7         69         15         40
159  2017          7         65         15         39
160  2017          8         64         15         37
161  2017          6         59         11         37
162  2017          7         56         11         34
163  2017         11         56         12         34
164  2017         10         63         13         35
165  2017         10         64         15         36
166  2017         11         66         16         35
167  2017          8         55         14         29
168  2018          7         59         13         30
169  2018         10         61         13         32
170  2018         11         62         13         32
171  2018         11         63         15         31
172  2018         12         59         14         30
173  2018         10         57         11         28
174  2018          8         54         10         29
175  2018         11         56         12         29
176  2018         12         62         13         29
177  2018         11         67         13         28
178  2018         12         60         14         26
179  2018          8         50         14         24
180  2019          8         55         11         24
181  2019         10         56         13         26
182  2019         10         59         14         26

[183 rows x 5 columns]

In [25]:
df = df.groupby(['year']).sum()

In [27]:
df.to_csv('dataset/year_multi_timeline.csv')